import React, { useEffect, useMemo, useState } from "react";
import { View, Text, ActivityIndicator, Pressable } from "react-native";
import AsyncStorage from "@react-native-async-storage/async-storage";
import WeatherService from "@/services/WeatherService";
import type { WeatherInfo } from "@/services/WeatherService";

type Coords = {
    latitude?: number;
    longitude?: number;
    lat?: number;
    lng?: number;
} | null;

type Item = {
    id: string;
    label: string;
    checked: boolean;
    autoGenerated?: boolean;
};

const CORE_ESSENTIALS = [
    "Passport",
    "Flight Ticket / Confirmation",
    "Phone Charger",
    "Power Bank",
    "Medicines",
    "Toiletries",
    "Wallet / Cards",
    "Travel Insurance Info",
];

const STORAGE_PREFIX = "packingChecklist:";

const AIPackingSuggestions = ({ coords, days = 1 }: { coords?: Coords; days?: number }) => {
    const [loading, setLoading] = useState(false);
    const [weather, setWeather] = useState<WeatherInfo | null>(null);
    const [items, setItems] = useState<Item[] | null>(null);

    const storageKey = useMemo(() => {
        if (!coords) return null;
        const lat = coords.latitude ?? (coords as any).lat;
        const lon = coords.longitude ?? (coords as any).lng;
        if (typeof lat !== "number" || typeof lon !== "number") return null;
        return `${STORAGE_PREFIX}${lat.toFixed(4)}:${lon.toFixed(4)}:d${days}`;
    }, [coords, days]);

    useEffect(() => {
        if (!coords) return;
        const lat = coords.latitude ?? (coords as any).lat;
        const lon = coords.longitude ?? (coords as any).lng;
        if (typeof lat !== "number" || typeof lon !== "number") return;

        let cancelled = false;
        (async () => {
            setLoading(true);
            try {
                const w = await WeatherService.getWeatherByCoords(Number(lat), Number(lon), days);
                if (cancelled) return;
                setWeather(w);
            } catch (e) {
                console.error("AIPackingSuggestions error:", e);
                setWeather(null);
            } finally {
                setLoading(false);
            }
        })();

        return () => {
            cancelled = true;
        };
    }, [coords, days]);

    // Build initial checklist when weather is available
    useEffect(() => {
        if (!weather) return;
        const dynamic = generatePackingList(weather);
        const allLabels = Array.from(new Set([...CORE_ESSENTIALS, ...dynamic]));

        const seedItems: Item[] = allLabels.map((label, idx) => ({ id: `${idx}_${label}`, label, checked: false, autoGenerated: dynamic.includes(label) }));

        setItems(seedItems);
    }, [weather]);

    // Load saved checked state
    useEffect(() => {
        if (!storageKey || !items) return;
        (async () => {
            try {
                const raw = await AsyncStorage.getItem(storageKey);
                if (!raw) return;
                const saved: Record<string, boolean> = JSON.parse(raw);
                setItems(prev => prev ? prev.map(it => ({ ...it, checked: !!saved[it.label] })) : prev);
            } catch (e) {
                console.warn("Failed loading packing checklist state", e);
            }
        })();
    }, [storageKey, items]);

    const persist = async (next: Item[]) => {
        if (!storageKey) return;
        try {
            const map: Record<string, boolean> = {};
            next.forEach(i => (map[i.label] = !!i.checked));
            await AsyncStorage.setItem(storageKey, JSON.stringify(map));
        } catch (e) {
            console.warn("Failed saving packing checklist state", e);
        }
    };

    const toggleItem = (id: string) => {
        if (!items) return;
        const next = items.map(i => i.id === id ? { ...i, checked: !i.checked } : i);
        setItems(next);
        persist(next);
    };

    if (!coords) return null;

    return (
        <View className="mb-6 bg-white p-4 rounded-xl border border-gray-100">
            <Text className="text-2xl font-outfit-bold mb-3">Packing Checklist</Text>

            {loading ? (
                <ActivityIndicator />
            ) : (
                <View>
                    {items && items.length ? (
                        <View>
                            {items.map(item => (
                                <Pressable key={item.id} onPress={() => toggleItem(item.id)} className="flex-row items-center py-2">
                                    <View className="w-6 h-6 mr-3 rounded-sm border border-gray-300 items-center justify-center" style={{ backgroundColor: item.checked ? '#6D28D9' : 'transparent' }}>
                                        <Text className="text-white text-sm">{item.checked ? '✓' : ''}</Text>
                                    </View>
                                    <Text className="text-base flex-1">{item.label}</Text>
                                    {item.autoGenerated ? <Text className="text-sm text-gray-400">AI</Text> : null}
                                </Pressable>
                            ))}
                        </View>
                    ) : (
                        <Text className="text-gray-600">No checklist available.</Text>
                    )}
                </View>
            )}
        </View>
    );
};

const generatePackingList = (w: WeatherInfo) => {
    const items = new Set<string>();
    const cond = (w.condition || "").toLowerCase();
    const feels = typeof w.feelsLikeC === "number" && !Number.isNaN(w.feelsLikeC) ? w.feelsLikeC : w.tempC;
    const rain = typeof w.chanceOfRain === "number" ? w.chanceOfRain : (w.forecast && w.forecast[0]?.chanceOfRain) ?? 0;

    // Snowy
    if (cond.includes("snow") || (w.forecast && w.forecast.some(fd => (fd.tempMinC !== null && fd.tempMinC <= 2) && (fd.chanceOfRain && fd.chanceOfRain > 30)))) {
        items.add("Thermal Wear");
        items.add("Heavy Jacket");
        items.add("Boots");
        items.add("Warm Gloves");
        items.add("Warm Socks");
    }

    // Rainy
    if (rain >= 50 || cond.includes("rain") || cond.includes("drizzle") || cond.includes("shower")) {
        items.add("Umbrella");
        items.add("Raincoat");
        items.add("Waterproof Shoes");
        items.add("Quick-dry Clothes");
    }

    // Cold
    if (typeof feels === "number" && feels <= 10) {
        items.add("Jacket");
        items.add("Sweater");
        items.add("Warm Socks");
        items.add("Gloves");
    }

    // Hot / Sunny
    if (typeof feels === "number" && feels >= 25) {
        items.add("T-Shirts");
        items.add("Shorts");
        items.add("Sunglasses");
        items.add("Sunscreen");
        items.add("Hat");
    }

    // Mild / Layering
    if (items.size === 0) {
        items.add("Light Jacket");
        items.add("Layers (T-Shirt + Sweater)");
    }

    // Windy
    if ((w.windKph ?? 0) > 40) items.add("Windbreaker");

    // Always useful
    items.add("Comfortable Shoes");
    items.add("Chargers & Adapter");

    return Array.from(items);
};

export default AIPackingSuggestions;
